### ISSUE TITLE
game's review 

### ISSUE THREAD

**Issue by SamPham2020** [chilkacastro/Final-Toby-s-Adventure-Game#1]
I have encountered some problems while playing the game:
- if played, quit, and went back, music will be duplicated. (Maybe put music static, then class music stop when click quit 
- not sure if it's Greenfoot bug, duplicated dogs' images, cannot go to level 3 ( just happened sometimes) 

The game has great graphic, content, and there are many efforts put to it.
Great job, I have a lot of fun playing this game. 
Let's work together in some projects in the future
https://user-images.githubusercontent.com/73408747/101440822-a9a8a480-38e5-11eb-9f86-58595b02a455.PNG
https://user-images.githubusercontent.com/73408747/101440814-a31a2d00-38e5-11eb-8ffd-5e0529710116.PNG

**Comment by chilkacastro** [comment]
Hi Hong! @SamPham2020 
Thanks for noticing those errors. XD I forgot to fixed those parts yesterday.  Btw, which music was looping? 
I actually tried your game several times today. But I don't know if my Greenfoot has a bug or it was your game.  I'll write it down on your GitHub account so you can still check if there is a bug or it's just my Greenfoot having issues :)

**Comment by SamPham2020** [comment]
the music when we start to play
