### ISSUE TITLE
Game review

### ISSUE THREAD

**Issue by gbouzon** [chilkacastro/Final-Toby-s-Adventure-Game#2]
I really liked playing your game! The little pop-up messages were very helpful and I love your screens, they look amazing.

Suggestion:
Add some sound normalization. Some sounds are very loud and others not as much, so there's a significant gap there.
Slow animation down. The dog's paws were moving really fast so it's difficult to notice the animation when the dog is 'running'. Very cute dog btw.

You guys did a very nice job, I specially like the little details you added.

**Comment by Nicosil** [comment]
That's not an issue. It's an intended feature, for example a Train sound should be louder than other sounds so it's completely intended. Furthermore, if all sounds were normalized it would be harder to differentiate between the unique sounds that I put a lot of work and thinking into.

**Comment by Nicosil** [comment]
Anyways I appreciate the input, my team will make sure to return the favor by giving our own constructive criticism for your game.
