### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by AtozZone** [chilkacastro/Final-Toby-s-Adventure-Game#3]
I love the game alot you guys made it very interesting
One part is I think for lvl 1 and 3 more of a way to get points as lvl 2 has the more amount of ways to get points.
One part I really enjoyed was that the difficulty of it as it is not too diffult but not too easy

**Comment by chilkacastro** [comment]
Thank you for testing it. Btw, what do you think of the scoring? Do you think player should have initial 10000 pts? or I should lower it down? Feel free to give more suggestions

**Comment by AtozZone** [comment]
I was thinking for scoring the points they should get would be from the stuff they collect
